[package]
name = "simag_core"
version = "0.0.1"
authors = ["IDG <iduartgomez@gmail.com>"]

[dependencies]
nom = { version = "^2.1", features = ["verbose-errors"] }
chrono = "^0.3"
crossbeam = "^0.2"
float-cmp = "^0.2"
termion = "^1.3"

[[bin]]
name = "repr"
path = "src/lang/repl.rs"
