[package]
name = "simag"
version = "0.0.1"
authors = ["IDG <iduartgomez@gmail.com>"]

[dependencies]
nom = { version = "^2.1.0", features = ["verbose-errors"] }
chrono = "*"
crossbeam = "^0.2"
float-cmp = "*"
