[package]
name = "simag_maths"
version = "0.0.1"
authors = ["IDG <iduartgomez@gmail.com>"]

[dependencies]
float-cmp = "*"
# ndarray = "^0.8"
itertools = "*"
rand = "^0.3"
uuid = { version = "^0.4", features = ["v4"] }
